name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        uses: actions/checkout@main

      - name: Run a multi-line script
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: master
