name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      #- name: Run a one-line script
      #  uses: actions/checkout@main

      - name: merge
        uses: devmasx/merge-branch@main
        with:
          type: now
          from_branch: dev
          target_branch: main
